# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Don't run pre-commit on files under third-party/
exclude: |
  (?x)^(
    (third-party/.*)|
    docs/_static.* |
    others/*
  )

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    types: [text]
  - id: check-added-large-files
    args: ['--maxkb=1024']

# - repo: https://github.com/psf/black
#   rev: 24.8.0
#   hooks:
#   - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi ]
    args: [ --fix ]
  # Run the formatter.
  - id: ruff-format
    types_or: [ python, pyi ]
